### ISSUE TITLE
Presetting credit card number before the page is rendered

### ISSUE THREAD

**Issue by bassrock** [stripe/jquery.payment#117]
When presetting the credit-card number using the value field before the page is rendered the library does not set the identified and card type class variables to indicate a valid card number.

**Comment by judgej** [comment]
I am finding it is also not formatting it. Are you finding that too, or would that be a different issue?

**Comment by jenanwise** [comment]
@bassrock or @judgej Can you create a minimal reproduction test case with jsfiddle?

**Comment by judgej** [comment]
That's a blast from the past! I'll try and dig out what I was working on. I can't remember if we carried on with this or use an alternative gateway.

**Comment by jenanwise** [comment]
:grin: Thanks!

**Comment by bassrock** [comment]
Yea so basically its if the input field has a value assigned to it on page load. will look to do a quick js fiddle

**Comment by judgej** [comment]
Hmm, coming back. We are using it on a site with OmniPay (Authorize.Net and SagePay), but not the stripe payment gateway. It is just used to make the CC entry a little more friendly and to cut down on front-end errors.

In the dev environment, I was setting the CC number in the form to a test card so I did not need to keep entering it by hand. The CC number was displaying, but without any formatting; the numbers were not grouped into sets of four digits and the date was formatted strangely.

I've just gone back into the dev system, and in the year past, PHP has been updated by a few versions, which as thrown some other errors in that I need to fix first. If I get this working, I'll post some details, but from what I remember it was as simple as populating the credit card number field in the form when it is first delivered to the browser.

**Comment by bassrock** [comment]
Alright here is an example based on the sample. Basically there is a preset value and it is not formatting the preset value.

https://jsfiddle.net/k561btds/

**Comment by judgej** [comment]
Great example. Same applies to the date (`cc-exp`) if set something like `value="0606"`

**Comment by jenanwise** [comment]
Thanks @bassrock and @judgej. It looks like you were using `https://raw.githubusercontent.com/stripe/jquery.payment/master/lib/jquery.payment.min.js` in that fiddle, which doesn't work, because github doesn't want you to use it as a CDN and doesn't set content type properly.You can use something like rawgit to get a fiddle-friendly url like `https://rawgit.com/stripe/jquery.payment/v1.3.0/lib/jquery.payment.js`.

You're correct that we don't format already-present values -- the api only listens for changes. If you want to format an input with an existing value, you can just add `.trigger('change')` on, e.g. `$('.cc-number').payment('formatCardNumber').trigger('change');`.

See [this updated fiddle](https://jsfiddle.net/k561btds/5/)

Hope that helps!
