### ISSUE TITLE
.payment('formatCardNumber') suppresses onchange events when pasting.

### ISSUE THREAD

**Issue by williamsjj** [stripe/jquery.payment#136]
If you attach .payment('formatCardNumber') to an input element, onchange only fires for numbers typed in. If you paste and then change focus, onchange doesn't fire for any attached listeners.

**Comment by jamesreggio** [comment]
I'm not able to reproduce this issue in the latest OSX Chrome, and the paste event doesn't appear to receive special handling in the code. Let me know which browser and version of the plugin you're using, and I'd be happy to investigate.

**Comment by milesmatthias** [comment]
@jamesreggio I'm able to reproduce this on an iPhone (latest iOS) in Safari and a Samsung G6 (Android 5) in Chrome. This seems to be a mobile only issue as it doesn't happen on my latest Chrome, OS X either.

**Comment by milesmatthias** [comment]
The change event on mobile (having nothing to do with this plugin) has been a [documented issue](http://stackoverflow.com/a/10544704) apparently. What was causing this issue for me is the `setTimeout` [setting the value on the next tick](https://github.com/stripe/jquery.payment/commit/273d79a08c82795eb24ec36463055e973abfe43c).

We listen to the `change` event to bind the input's value to a model. When I listen to the `paste` event instead, I have to do a `setTimeout` for at least 2ms in order to actually get the value of the input. I'll send a PR for the README to add a note for people who are doing data binding like this too.

**Comment by milesmatthias** [comment]
Forking this repo produces an older/different version of this repo, so I'm not able to submit a PR like usual, but here's some text for you to append to the `Mobile recommendations` section in the README:


> We also recommend you verify your data binding works when pasting values if you're using AJAX. Due to the events that [mobile inputs fire](https://github.com/stripe/jquery.payment/commit/273d79a08c82795eb24ec36463055e973abfe43c), we set the value of an input on the next clock tick with a `setTimeout`. This means that if you also bind to the `change` or `paste` events to bind the value to a model, the value you get won't be filled in yet. For those reasons, we recommend getting the values of the inputs when the user submits the form if you're using AJAX:
> 
> ```js
> $form.on("submit", function(e) {
>   e.preventDefault();
> 
>   var cardnum = $("#card-num-input").val(),
>       cardexp = $("#card-exp-input").val(),
>       cardcvc = $("#card-cvc-input").val();
> 
>   // do stuff.
> 
>   return false;
> });
> ```
>
