### ISSUE TITLE
`$ is not defined` on CommonJS, should load $ as an option

### ISSUE THREAD

**Issue by mikemaccana** [stripe/jquery.payment#152]
Currently:

    var $ = require('jquery');
    require('jquery-payment);

Returns:

    Uncaught ReferenceError: $ is not defined

You have to hack around it by adding a global:

    var $ = require('jquery');
    window.$ = $;
    require('jquery-payment);

A better option would be to simply have the jQuery instance to extend as an option (i.e., use dependency injection). 

    require('jquery-payment)($);

This would normally be done in a UMD - I was about to send a patch - but the lib isn't using one right now. Any objections if I add one?

**Comment by SlexAxton** [comment]
It's tough to add UMD to a project without like 20 major version releases, because you end up trapped in bad keyword assumptions across the web (`if ('define' in window)...`).

I don't know if we could responsibly release backwards compatible update to support your use case and *also* use AMD right away. Because of this, I'd rather touch as little as possible, but allow jQuery "setting/overriding" without picking a module format pattern.

**SWEAR TO ME**

Feel free to argue.

**Comment by mikemaccana** [comment]
I'd have thought UMDs been around long enough a lot of the edge cases are known, but allowing jQuery as an optional argument for npm/browserify/commonjs seems legit. Will have a play and see what I can do...

**Comment by mikemaccana** [comment]
Ah, with the IIFE (which is I guess is there for <script> tag users) looks like there's no way to provide an optional arg specifying a custom jQuery to extend :\

PS. I did notice **SWEAR TO ME** and lol, but at the time could not think of anything witty to say in response so pretended I didn't see it as I did not want to enter into some kind of humour-based arms race.

**Comment by jondavidjohn** [comment]
I've forked jQuery.payment to remove the jQuery dependency and target more platforms like browserify / CommonJS / node.

https://github.com/jondavidjohn/payform

Had a conversation going to roll this back upstream at https://github.com/jondavidjohn/payform/issues/1 but it seems to have stalled.

**Comment by bendrucker** [comment]
If you're using Browserify, give [browserify-shim](https://github.com/thlorenz/browserify-shim) a spin.

**Comment by rockfield** [comment]
@SlexAxton 
have the same problem using it as jQuery plugin. I can't use $ for jQuery so there is defined Prototype.

coffee script generator gives us the following code:
https://github.com/stripe/jquery.payment/blob/master/lib/jquery.payment.js

It's not hard to provide jQuery as a local variable:
```javascript
// Generated by CoffeeScript 1.7.1
(function($) {
/// . . .
}).call(this, jQuery);
```

I'd fork it and provide pull request but I don't know coffee yet.

**Comment by pilou** [comment]
+1 on making this AMD compatible.

jQuery dependency is not an issue for me, after all this is a jquery plugin.
Neither and issue the lack of the module format, but `$.payment` could be returned.

An AMD dependency could be set, so loading with requirejs wont need a shim.

Creating a 'paralell' release like @jondavidjohn did, seems like the worst option, because resolved issues here can only be fully manually cherry picked to his realease. And I think it wont be happening, as its not happening since February.

 Removing dependencies, and publish and independent module, AND a pquery plugin based on the independent module is a nice to have.

**Comment by jenanwise** [comment]
We're going to close this for now. We're looking into ways to make jquery.payment's logic work without a jquery dependency.

**Comment by jondavidjohn** [comment]
@jenanwise Just in case I need to say it again, I've done a lot of work in that regard on jondavidjohn/payform and I'd be happy to pass it back to stripe... (see full discussion in jondavidjohn/payform#1)

**Comment by jenanwise** [comment]
@jondavidjohn, I sincerely apologize for the lack of clarity here! You've clearly done a lot of solid work, and payform looks fantastic.

However, we've come to believe that jquery.payment has more fundamental issues than its jquery dependency. Currently it handles card brand lookup, cross-browser event handling, caret positioning, card number pretty printing, input masking, etc. Entangling these things makes maintenance difficult and forces us to compromise on the quality and testability of each of the individual components. As such, I'm hesitant to merge large changes back into this library until we've thought about how to break it into manageable modules.
