### ISSUE TITLE
formatCardNumber kills change events in IE11

### ISSUE THREAD

**Issue by jscheel** [stripe/jquery.payment#159]
change events are never fired in IE11 if formatCardNumber is set on that input.

**Comment by jscheel** [comment]
Reproducible: http://output.jsbin.com/yujefiqari/1

**Comment by jscheel** [comment]
Looks like reFormatCardNumber rewrites the input during the input event, but outside the initial event loop, which in some what kills the change event. Been testing for a bit, but browserstack is killing me with it's slowness.

**Comment by jscheel** [comment]
same with reFormatNumeric

**Comment by Saidbek** [comment]
having the same issue with IE11

**Comment by indextwo** [comment]
Having tried your fiddle, it looks like binding solely to the `change` event doesn't work in Firefox 40 either. Although it's a mildly different issue, in my own script I'm binding to `input change focusin paste`, which works for the most part except when spaces are automatically inserted between the numbers (which should come under `change`, as far as I'm aware) - it waits until I add another number, and then suddenly adds the last number of the set before the space, the space, and then the next number. I can't figure out how fix it.

**Comment by jenanwise** [comment]
Sorry for the late reply!

I believe this is actually an issue with browsers disagreeing (and possibly jquery itself). [Here](http://jsfiddle.net/gnnjd1h7/) is a jsfiddle that demonstrates the issue: using `$(input).val(newVal)` will kill change events in Safari and Chrome under some circumstances, but not in Firefox. You can find more discussion about browsers disagreeing about 'change' events [here](https://code.google.com/p/chromium/issues/detail?id=92492#c33). Since 'change' is so non-standard, I recommend binding on other events as well (just like `jquery.payment` itself does).

**Comment by adaddeo** [comment]
We are still seeing this issue on IE11. @jenanwise we are binding to 'input' and 'paste' events as you suggested, but as @indextwo pointed out the `e.preventDefault()` also prevents bubbling in IE11. We followed his fix and the issue was resolved.
