### ISSUE TITLE
Unable to undo after paste in Firefox

### ISSUE THREAD

**Issue by joshkel** [stripe/jquery.payment#177]
When using the demo page, if I paste a complete credit card number into the credit card input then press ⌘-Z to undo, the cursor jumps back to the beginning of the input, but the pasted digits aren't removed.

Undoing after pasting 1, 2, or 3 digits into an empty credit card input works. The bug seems to only be triggered if pasting causes spaces to be inserted.

Observed in Firefox 40 for OS X. Chrome 45 and Safari both work fine.

**Comment by jenanwise** [comment]
This definitely stinks! Unfortunately, I don't see a way to fix it without breaking more-critical behavior in other browsers. The issue is this: pasting triggers our `reformat*` handlers, which set the value asynchronously, but in Firefox (version 40), changes to an input field that are triggered asynchronously are not grouped into a single event in the undo buffer. We could make the handler synchronous, but that breaks cursor position and pasting itself (not just undo) in some mobile browsers (e.g. old Android Browser). Since pasting is more critical than paste-undo, we can't do that. Note that paste-undo is also non-functional in most IE versions.

**Comment by joshkel** [comment]
Makes sense. Thank you for the follow-up and explanation.
