### ISSUE TITLE
data-stripe

### ISSUE THREAD

**Issue by hardlynoticable** [stripe/jquery.payment#191]
I'm confused; I thought we were supposed to use the "data-stripe" attribute instead of "value"; to prevent credit card data from being submitted to the server.  

This code seems to be using the wrong tags; am I mistaken?

**Comment by richardcornish** [comment]
@hardlynoticable I think you might be mixing up a few concepts.

The `name` attribute on `<input>`s is removed to prevent submission of sensitive data to the server. From the [Stripe docs](https://stripe.com/docs/tutorials/forms):

> Note how input fields representing sensitive card data (number, CVC, expiration month and year) do not have a "name" attribute. This prevents them from hitting your server when the form is submitted.

The `value` attribute would be for [editing credit cards](https://stripe.com/blog/multiple-cards) that already exists that you want your user to change.

The `data-stripe` attribute on `<input>`s is added to custom forms when you want a custom form but don't want to manually manage the submission of the object containing the data. They are simply HTML5 convenience attributes. My guess for the different ways of doing it is that people have preferences when it comes to selecting months and years via `<input>` or `<select>`.

[With](https://stripe.com/docs/tutorials/forms#create-a-single-use-token) `data-stripe` attributes in HTML:

```
Stripe.card.createToken($form, stripeResponseHandler);
```

[Without](https://stripe.com/docs/stripe.js#card-createToken) `data-stripe` attributes in HTML:

```
Stripe.card.createToken({
  number: $('.card-number').val(),
  cvc: $('.card-cvc').val(),
  exp_month: $('.card-expiry-month').val(),
  exp_year: $('.card-expiry-year').val()
}, stripeResponseHandler);
```

You can make a custom form with or without `data-stripe` attributes and with or without jquery.payment, although you really should use jquery.payment, that's why it's there for custom forms without the Stripe Connect look and feel. Personally I like to have a little more control with two `<select>`s, so I go without `data-stripe` attributes.

**Comment by hardlynoticable** [comment]
You are correct; I did mix up the concepts.  When the form data is being sent to the server via ajaj nothing gets posted(putted, deleted, etc) except purposefully.  

If I'd thought about it for a second or two before I asked my question I would have realized that the data-stripe attribute is only important to people who are doing an html form submit.
