### ISSUE TITLE
using $.payment('formatCardNumber') with input type="tel" doesn't work properly

### ISSUE THREAD

**Issue by tomerb15** [stripe/jquery.payment#234]
When entering card number using the numbers keypad(as a result of type="tel")
not all key presses are being catch. You can view a full example here:
http://bootsnipp.com/fullscreen/55PbE

I tried it with chrome on several android devices.

**Comment by jenanwise** [comment]
As far as I can tell, this Chrome's "Automatic credit card filling is disabled..." popover fighting with our change handlers (which are definitely a lot slower than they should/could be). You'll only see that popup when using http instead of https, which won't matter for production environments, because you should only ever use https for production environments. It also only seems to lose entries when typing *really* fast (i.e. trying to break the form).

If you think this is something more specific or buggy, please let me know with more details! Specific problematic lines of code, and ideally video of the issue, would be great. Thank you!
