### ISSUE TITLE
Card number formatting strange behavior

### ISSUE THREAD

**Issue by icodk** [stripe/jquery.payment#271]
Try entring 3333333333 or 123456, 111111, 66666, 99999
No spaces added between 4 char groups
Not a major issue but... I thought you wanted to know

**Comment by arthurgouveia** [comment]
It will only add the spaces if the number is valid.

**Comment by developer-vtnetzwelt** [comment]
We are using Woocommerce in our website, but we are facing strange issue when typing Credit card information.

The problem when that option is either present or not present, manual entry of card details is difficult. The numbers will randomly populate and enter in random card details and makes it very hard to amend or delete/edit numbers 

Only on certain devices/browsers and keyboards does the error appear.
Please note: on some devices a 'scan new card' option will appear, that feature is fine and works well 

We need to find  a fix so that whenever manually entering card details nothing is automatically populated and a user just has to enter in their details

Please note: this is currently a repeatable error on my phone. My Samsung mobile model is - Samsung Galaxy S7. SM-G930F, Android version is 7.0, Samsung keyboard is version 1.5.47, Broswer: Google Chrome

Please note: If I change my keyboard from the default Samsung Keyboard to GBoard then the problem does not occur and I can enter in details fine

**Comment by jenan-stripe** [comment]
As mentioned above, only known/valid formats are formatted.
